import { CardPhoto } from "@/entities/CardPhoto";
import type { Metadata } from 'next';
import Link from "next/link";

export const metadata: Metadata = {
  title: "Фото альбом",
  description: "Generated by create next app",
};

const albums = [
  {
    id: 1123123123123,
    title: "qwertty",
    count: 3,
    file: 'https://avatars.mds.yandex.net/i?id=9045280b715298fb7b72fa6d88fe92c6_l-4519035-images-thumbs&n=13'
  },
  {
    id: 2123231,
    title: "qwertty2222",
    count: 12,
    file: 'https://s1.1zoom.ru/big3/26/357022-svetik.jpg'
  },
  {
    id: 4444444444,
    title: "qwertt22222y",
    count: 13,
    file: 'https://i.pinimg.com/736x/6f/82/b4/6f82b495223d134834f282ea809846d7.jpg'
  },
  {
    id: 341241,
    title: "qwertty2222",
    count: 13,
    file: 'https://wallbox.ru/resize/2560x1440/wallpapers/main/201428/4b0f817828c497c.jpg'
  },
]

export default async function Home() {
  return (
    <main className="max-w-[1200px] w-full flex-grow">
      <div className="grid auto-fill-[320px] gap-5 px-5 py-2">
        {
          albums.map((album) => {
            return (
              <Link key={album.id} style={{ display: "contents" }} href="/album/1">
                <CardPhoto
                  img={album.file}
                  title={album.title}
                  count={album.count} />
              </Link>
            )
          })
        }
      </div>
    </main>
  );
}
